import "./globals.css";

export const metadata = {
    title: "SNEAK3R 👟 SHOP",
    description: "Generated by create next app",
};

import PageWrapper from "@/layout/PageWrapper/PageWrapper";

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <PageWrapper>{children}</PageWrapper>
            </body>
        </html>
    );
}
